package io.stateproof.sync

/**
 * Marks a test as generated by StateProof.
 *
 * This annotation enables the sync algorithm to:
 * - Identify generated tests by their path hash
 * - Track when the test was generated
 * - Detect if expected transitions need updating
 *
 * @param pathHash Unique CRC32 hash of the full traversal path (e.g., "97BC3A21")
 * @param generatedAt ISO-8601 timestamp when the test was generated
 * @param schemaVersion Version of the generation schema (for future migrations)
 * @param expectedTransitions The expected transition strings at generation time
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class StateProofGenerated(
    val pathHash: String,
    val generatedAt: String,
    val schemaVersion: Int = 1,
    val expectedTransitions: Array<String> = [],
)

/**
 * Marks a test as obsolete - the path no longer exists in the state machine.
 *
 * Obsolete tests are NOT auto-deleted. They are marked and disabled,
 * requiring manual review before deletion.
 *
 * @param reason Human-readable explanation of why the test is obsolete
 * @param markedAt ISO-8601 timestamp when the test was marked obsolete
 * @param originalPath The original path that no longer exists
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class StateProofObsolete(
    val reason: String,
    val markedAt: String,
    val originalPath: String,
)

/**
 * Marker comments used to delimit generated code sections.
 *
 * Code between BEGIN and END markers is managed by StateProof.
 * Code outside these markers (user implementation) is preserved during sync.
 */
object StateProofMarkers {
    /** Start of generated expected transitions block */
    const val BEGIN_EXPECTED = "// ▼▼▼ STATEPROOF:EXPECTED - Do not edit below this line ▼▼▼"

    /** End of generated block */
    const val END = "// ▲▲▲ STATEPROOF:END ▲▲▲"

    /** User implementation separator (informational, not parsed) */
    const val USER_SECTION = "// ══════════════════════════════════════════════════════════"

    /** User section header */
    const val USER_HEADER = "// User implementation below (preserved across regeneration)"

    /** Regex to match BEGIN marker */
    val BEGIN_PATTERN = Regex("""//\s*▼+\s*STATEPROOF:EXPECTED.*▼+""")

    /** Regex to match END marker */
    val END_PATTERN = Regex("""//\s*▲+\s*STATEPROOF:END.*▲+""")
}
