package io.stateproof.screenshot

import io.stateproof.testgen.SimpleTestCase

data class ScreenshotCodeGenConfig(
    val packageName: String,
    val testClassName: String,
    val machineSlug: String,
    val harnessFactoryExpression: String,
    val captureMode: ScreenshotCaptureMode = ScreenshotCaptureMode.MOVIE,
    val additionalImports: List<String> = emptyList(),
    val indent: String = "    ",
)

object ScreenshotTestCodeGenerator {

    fun generateTestFile(
        config: ScreenshotCodeGenConfig,
        tests: List<SimpleTestCase>,
        timestamp: String,
    ): String {
        val renderedTests = tests.map { generateSingleTest(config, it, timestamp) }
        return generateTestFileFromRenderedTests(
            config = config,
            renderedTests = renderedTests,
            timestamp = timestamp,
            totalTests = tests.size,
        )
    }

    fun generateTestFileFromRenderedTests(
        config: ScreenshotCodeGenConfig,
        renderedTests: List<String>,
        timestamp: String,
        totalTests: Int,
    ): String = buildString {
        appendLine("package ${config.packageName}")
        appendLine()
        appendLine("import app.cash.paparazzi.Paparazzi")
        appendLine("import io.stateproof.screenshot.StateProofScreenshotGenerated")
        appendLine("import io.stateproof.screenshot.StateProofScreenshotObsolete")
        appendLine("import kotlinx.coroutines.runBlocking")
        appendLine("import org.junit.Ignore")
        appendLine("import org.junit.Rule")
        appendLine("import org.junit.Test")
        appendLine("import kotlin.test.assertEquals")
        config.additionalImports.forEach { importLine ->
            appendLine("import $importLine")
        }
        appendLine()
        appendLine("/**")
        appendLine(" * Generated by StateProof Screenshot - Do not edit manually.")
        appendLine(" *")
        appendLine(" * Generated at: $timestamp")
        appendLine(" * Total tests: $totalTests")
        appendLine(" */")
        appendLine("class ${config.testClassName} {")
        appendLine("${config.indent}@get:Rule")
        appendLine("${config.indent}val paparazzi = Paparazzi()")
        appendLine()
        renderedTests.forEach { renderedTest ->
            append(renderedTest)
            appendLine()
        }
        appendLine("${config.indent}private fun buildSnapshotName(pathHash: String, stepIndex: Int, stateName: String): String {")
        appendLine("${config.indent}${config.indent}val safeState = stateName.replace(Regex(\"[^A-Za-z0-9]+\"), \"-\").trim('-').ifBlank { \"unknown\" }")
        appendLine("${config.indent}${config.indent}val safeMachine = \"${config.machineSlug}\"")
        appendLine("${config.indent}${config.indent}val step = stepIndex.toString().padStart(2, '0')")
        appendLine("${config.indent}${config.indent}return \"\${safeMachine}_\${pathHash}_\${step}_\${safeState}\"")
        appendLine("${config.indent}}")
        appendLine("}")
    }

    fun generateSingleTest(
        config: ScreenshotCodeGenConfig,
        testCase: SimpleTestCase,
        timestamp: String,
    ): String = buildString {
        val indent = config.indent
        val hash = extractHash(testCase.name)
        appendLine("${indent}@StateProofScreenshotGenerated(")
        appendLine("${indent}${indent}pathHash = \"$hash\",")
        appendLine("${indent}${indent}generatedAt = \"$timestamp\",")
        appendLine("${indent}${indent}schemaVersion = 1,")
        appendLine("${indent}${indent}captureMode = \"${config.captureMode.name}\",")
        appendLine("${indent})")
        appendLine("${indent}@Test")
        appendLine("${indent}fun `${testCase.name}`() = runBlocking {")
        appendLine("${indent}${indent}//${testCase.path.joinToString("_")}")
        appendLine()
        appendLine("${indent}${indent}${StateProofScreenshotMarkers.BEGIN_EXPECTED}")
        appendLine("${indent}${indent}val expectedTransitions = listOf(")
        testCase.expectedTransitions.forEach { transition ->
            appendLine("${indent}${indent}${indent}\"$transition\",")
        }
        appendLine("${indent}${indent})")
        appendLine("${indent}${indent}${StateProofScreenshotMarkers.END}")
        appendLine()
        appendLine("${indent}${indent}${StateProofScreenshotMarkers.USER_SECTION}")
        appendLine("${indent}${indent}${StateProofScreenshotMarkers.USER_HEADER}")
        appendLine("${indent}${indent}${StateProofScreenshotMarkers.USER_SECTION}")
        appendLine()
        appendLine("${indent}${indent}val harness = ${config.harnessFactoryExpression}")
        appendLine("${indent}${indent}try {")
        appendLine("${indent}${indent}${indent}harness.beforePath(expectedTransitions)")
        appendLine("${indent}${indent}${indent}val sm = harness.createStateMachine()")
        appendLine()
        appendLine("${indent}${indent}${indent}val initialStateName = expectedTransitions.firstOrNull()?.substringBefore('_')")
        appendLine("${indent}${indent}${indent}${indent}?: (sm.currentState::class.simpleName ?: \"Initial\")")
        appendLine("${indent}${indent}${indent}paparazzi.snapshot(")
        appendLine("${indent}${indent}${indent}${indent}name = buildSnapshotName(pathHash = \"$hash\", stepIndex = 0, stateName = initialStateName),")
        appendLine("${indent}${indent}${indent}) {")
        appendLine("${indent}${indent}${indent}${indent}harness.render(sm.currentState)")
        appendLine("${indent}${indent}${indent}}")
        appendLine()
        appendLine("${indent}${indent}${indent}for ((index, transition) in expectedTransitions.withIndex()) {")
        appendLine("${indent}${indent}${indent}${indent}val currentLog = sm.getTransitionLog()")
        appendLine("${indent}${indent}${indent}${indent}if (currentLog.size <= index) {")
        appendLine("${indent}${indent}${indent}${indent}${indent}val event = harness.eventForTransition(sm.currentState, transition)")
        appendLine("${indent}${indent}${indent}${indent}${indent}sm.onEvent(event)")
        appendLine("${indent}${indent}${indent}${indent}${indent}harness.awaitIdle(sm)")
        appendLine("${indent}${indent}${indent}${indent}}")
        appendLine()
        appendLine("${indent}${indent}${indent}${indent}val updatedLog = sm.getTransitionLog()")
        appendLine("${indent}${indent}${indent}${indent}check(updatedLog.size > index) {")
        appendLine("${indent}${indent}${indent}${indent}${indent}\"Expected transition at index \$index was not produced: \$transition\"")
        appendLine("${indent}${indent}${indent}${indent}}")
        appendLine("${indent}${indent}${indent}${indent}assertEquals(transition, updatedLog[index])")
        appendLine()
        appendLine("${indent}${indent}${indent}${indent}val targetState = transition.substringAfterLast('_', \"Unknown\")")
        appendLine("${indent}${indent}${indent}${indent}paparazzi.snapshot(")
        appendLine("${indent}${indent}${indent}${indent}${indent}name = buildSnapshotName(pathHash = \"$hash\", stepIndex = index + 1, stateName = targetState),")
        appendLine("${indent}${indent}${indent}${indent}) {")
        appendLine("${indent}${indent}${indent}${indent}${indent}harness.render(sm.currentState)")
        appendLine("${indent}${indent}${indent}${indent}}")
        appendLine("${indent}${indent}${indent}}")
        appendLine()
        appendLine("${indent}${indent}${indent}assertEquals(expectedTransitions, sm.getTransitionLog())")
        appendLine("${indent}${indent}} finally {")
        appendLine("${indent}${indent}${indent}harness.close()")
        appendLine("${indent}${indent}}")
        appendLine("${indent}}")
    }

    fun updateExistingTest(
        existingTest: ScreenshotFileParser.ParsedScreenshotTest,
        newTransitions: List<String>,
        timestamp: String,
        indent: String = "    ",
    ): String {
        val original = existingTest.fullText
        val beginMatch = StateProofScreenshotMarkers.BEGIN_PATTERN.find(original)
        val endMatch = StateProofScreenshotMarkers.END_PATTERN.find(original)
        if (beginMatch == null || endMatch == null) {
            return original
        }

        val newGeneratedSection = buildString {
            appendLine()
            appendLine("${indent}${indent}val expectedTransitions = listOf(")
            newTransitions.forEach { transition ->
                appendLine("${indent}${indent}${indent}\"$transition\",")
            }
            appendLine("${indent}${indent})")
            append("${indent}${indent}")
        }

        val before = original.substring(0, beginMatch.range.last + 1)
        val after = original.substring(endMatch.range.first)
        val updatedBefore = updateAnnotationTimestamp(before, timestamp)
        return updatedBefore + newGeneratedSection + after
    }

    fun markTestObsolete(
        existingTest: ScreenshotFileParser.ParsedScreenshotTest,
        reason: String,
        timestamp: String,
        indent: String = "    ",
    ): String {
        val original = existingTest.fullText
        if (existingTest.isObsolete) {
            return original
        }

        val insertPoint = when {
            original.contains("@StateProofScreenshotGenerated") -> original.indexOf("@StateProofScreenshotGenerated")
            original.contains("@Test") -> original.indexOf("@Test")
            else -> 0
        }

        val obsoleteAnnotation = buildString {
            appendLine("${indent}@StateProofScreenshotObsolete(")
            appendLine("${indent}${indent}reason = \"$reason\",")
            appendLine("${indent}${indent}markedAt = \"$timestamp\",")
            appendLine("${indent}${indent}originalPath = \"${existingTest.expectedTransitions.joinToString(" -> ")}\",")
            appendLine("${indent})")
            appendLine("${indent}@Ignore(\"StateProof Screenshot: Path obsolete since $timestamp\")")
        }

        return original.substring(0, insertPoint) + obsoleteAnnotation + original.substring(insertPoint)
    }

    private fun updateAnnotationTimestamp(text: String, newTimestamp: String): String {
        val pattern = Regex("""generatedAt\s*=\s*"[^"]+"""")
        return pattern.replace(text, """generatedAt = "$newTimestamp"""")
    }

    private fun extractHash(testName: String): String {
        val parts = testName.split("_")
        return if (parts.size >= 3) parts[2] else testName
    }
}
