package io.stateproof.screenshot

import androidx.compose.runtime.Composable
import io.stateproof.StateMachine

/**
 * Capture mode for generated screenshot tests.
 */
enum class ScreenshotCaptureMode {
    MOVIE,
}

/**
 * Harness contract implemented by consumer projects to drive screenshot tests.
 */
interface StateProofScreenshotHarness<STATE : Any, EVENT : Any> : AutoCloseable {

    /**
    * Creates a fresh state machine instance for one generated test path.
    */
    fun createStateMachine(): StateMachine<STATE, EVENT>

    /**
     * Resolves the event needed to execute a transition in "From_Event_To" format.
     */
    fun eventForTransition(currentState: STATE, transition: String): EVENT

    /**
     * Called before a generated path starts. Harnesses can use this to tune branch defaults.
     */
    fun beforePath(expectedTransitions: List<String>) = Unit

    /**
     * Renders the current state to be captured by Paparazzi.
     */
    @Composable
    fun render(state: STATE)

    /**
     * Waits until the machine is idle after event dispatch.
     */
    suspend fun awaitIdle(machine: StateMachine<STATE, EVENT>) {
        machine.awaitIdle()
    }

    override fun close() = Unit
}

/**
 * Marks a screenshot test generated by StateProof.
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class StateProofScreenshotGenerated(
    val pathHash: String,
    val generatedAt: String,
    val schemaVersion: Int = 1,
    val captureMode: String = "MOVIE",
)

/**
 * Marks a screenshot test as obsolete when its path no longer exists.
 */
@Target(AnnotationTarget.FUNCTION)
@Retention(AnnotationRetention.RUNTIME)
annotation class StateProofScreenshotObsolete(
    val reason: String,
    val markedAt: String,
    val originalPath: String,
)

/**
 * Marker comments used for sync-safe expected transition blocks.
 */
object StateProofScreenshotMarkers {
    const val BEGIN_EXPECTED = "// ▼▼▼ STATEPROOF:SCREENSHOTS_EXPECTED - Do not edit below this line ▼▼▼"
    const val END = "// ▲▲▲ STATEPROOF:SCREENSHOTS_END ▲▲▲"
    const val USER_SECTION = "// ══════════════════════════════════════════════════════════"
    const val USER_HEADER = "// User implementation below (preserved across regeneration)"

    val BEGIN_PATTERN = Regex("""//\s*▼+\s*STATEPROOF:SCREENSHOTS_EXPECTED.*▼+""")
    val END_PATTERN = Regex("""//\s*▲+\s*STATEPROOF:SCREENSHOTS_END.*▲+""")
}
